# frozen_string_literal: true

require 'net/http'
require 'uri'
require 'json'
require 'faraday'
require 'faraday/net_http_persistent'

require 'fcc4d/version'

require 'fcc4d/client'
require 'fcc4d/resource'

require 'fcc4d/countries'
require 'fcc4d/lookup'
require 'fcc4d/oauth'
require 'fcc4d/partners'
require 'fcc4d/push'
require 'fcc4d/sms'
require 'fcc4d/storage'
require 'fcc4d/storage/containers'
require 'fcc4d/storage/files'
require 'fcc4d/verification/email'
require 'fcc4d/shortener'
require 'fcc4d/shortener/links'
require 'fcc4d/app'
require 'fcc4d/app/conference'
require 'fcc4d/app/conference/calls'
require 'fcc4d/app/conference/meetings'
require 'fcc4d/conference'
require 'fcc4d/conference/callflows'
require 'fcc4d/conference/cdrs'
require 'fcc4d/conference/didgroups'
require 'fcc4d/conference/mdrs'
require 'fcc4d/conference/meetingrooms'
require 'fcc4d/conference/meetings'
require 'fcc4d/conference/v2/meeting_rooms'
require 'fcc4d/conference/v2/meetings'
require 'fcc4d/flexml'
require 'fcc4d/flexml/calls'
require 'fcc4d/mediator'
require 'fcc4d/mediator/bindings'
